/* This file was automatically generated by CasADi 3.6.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[9] = {18, 19, 20, 24, 25, 26, 30, 31, 32};
static const casadi_int casadi_s1[9] = {21, 22, 23, 27, 28, 29, 33, 34, 35};
static const casadi_int casadi_s2[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[30] = {6, 6, 0, 6, 11, 15, 18, 20, 21, 0, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5};
static const casadi_int casadi_s5[30] = {6, 6, 0, 1, 3, 6, 10, 15, 21, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[3] = {0, 0, 0};

static const casadi_real casadi_c0[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_ode_fun:(i0[12],i1[4],i2[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+6, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+30, *w14=w+42, *w15=w+48, *w16=w+84, *w17=w+120, *w18=w+156, *w19=w+165, *w20=w+174, *w21=w+183, *w22=w+192, *w23=w+201, *w24=w+237, *w25=w+243, *w26=w+246, *w27=w+252, *w28=w+258, *w29=w+264;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #3: @3 = input[0][2] */
  w3 = arg[0] ? arg[0][2] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #7: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #8: @8 = input[0][7] */
  w8 = arg[0] ? arg[0][7] : 0;
  /* #9: @9 = input[0][8] */
  w9 = arg[0] ? arg[0][8] : 0;
  /* #10: @10 = input[0][9] */
  w10 = arg[0] ? arg[0][9] : 0;
  /* #11: @11 = input[0][10] */
  w11 = arg[0] ? arg[0][10] : 0;
  /* #12: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #13: @13 = vertcat(@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @14 = @13[6:12] */
  for (rr=w14, ss=w13+6; ss!=w13+12; ss+=1) *rr++ = *ss;
  /* #15: (@0[:6] = @14) */
  for (rr=w0+0, ss=w14; rr!=w0+6; rr+=1) *rr = *ss++;
  /* #16: @14 = zeros(6x1) */
  casadi_clear(w14, 6);
  /* #17: @15 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 36, w15);
  /* #18: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #19: @1 = 1.05834e-08 */
  w1 = 1.0583361414712400e-08;
  /* #20: (@16[0] = @1) */
  for (rr=w16+0, ss=(&w1); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #21: @1 = 1.05834e-08 */
  w1 = 1.0583361414712400e-08;
  /* #22: (@16[7] = @1) */
  for (rr=w16+7, ss=(&w1); rr!=w16+8; rr+=1) *rr = *ss++;
  /* #23: @1 = 1.05834e-08 */
  w1 = 1.0583361414712400e-08;
  /* #24: (@16[14] = @1) */
  for (rr=w16+14, ss=(&w1); rr!=w16+15; rr+=1) *rr = *ss++;
  /* #25: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #26: (@16[21] = @1) */
  for (rr=w16+21, ss=(&w1); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #27: @1 = -1.71991e-08 */
  w1 = -1.7199142052564800e-08;
  /* #28: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #29: @1 = (@1*@2) */
  w1 *= w2;
  /* #30: (@16[33] = @1) */
  for (rr=w16+33, ss=(&w1); rr!=w16+34; rr+=1) *rr = *ss++;
  /* #31: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #32: @2 = 1.18747e-08 */
  w2 = 1.1874674422694799e-08;
  /* #33: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #34: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #35: @2 = (@2*@3) */
  w2 *= w3;
  /* #36: @1 = (@1+@2) */
  w1 += w2;
  /* #37: @2 = 5.75996e-08 */
  w2 = 5.7599641136459801e-08;
  /* #38: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #39: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #40: @2 = (@2*@3) */
  w2 *= w3;
  /* #41: @1 = (@1-@2) */
  w1 -= w2;
  /* #42: (@16[28] = @1) */
  for (rr=w16+28, ss=(&w1); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #43: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #44: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #45: @1 = (@1*@2) */
  w1 *= w2;
  /* #46: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #47: @1 = (@1*@2) */
  w1 *= w2;
  /* #48: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #49: @1 = (@1*@2) */
  w1 *= w2;
  /* #50: @2 = 5.75996e-08 */
  w2 = 5.7599641136459801e-08;
  /* #51: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #52: @2 = (@2*@3) */
  w2 *= w3;
  /* #53: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #54: @2 = (@2*@3) */
  w2 *= w3;
  /* #55: @3 = sin(@4) */
  w3 = sin( w4 );
  /* #56: @2 = (@2*@3) */
  w2 *= w3;
  /* #57: @1 = (@1-@2) */
  w1 -= w2;
  /* #58: (@16[34] = @1) */
  for (rr=w16+34, ss=(&w1); rr!=w16+35; rr+=1) *rr = *ss++;
  /* #59: @1 = -1.71991e-08 */
  w1 = -1.7199142052564800e-08;
  /* #60: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #61: @1 = (@1*@2) */
  w1 *= w2;
  /* #62: (@16[23] = @1) */
  for (rr=w16+23, ss=(&w1); rr!=w16+24; rr+=1) *rr = *ss++;
  /* #63: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #64: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #65: @1 = (@1*@2) */
  w1 *= w2;
  /* #66: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #67: @1 = (@1*@2) */
  w1 *= w2;
  /* #68: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #69: @1 = (@1*@2) */
  w1 *= w2;
  /* #70: @2 = 5.75996e-08 */
  w2 = 5.7599641136459801e-08;
  /* #71: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #72: @2 = (@2*@3) */
  w2 *= w3;
  /* #73: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #74: @2 = (@2*@3) */
  w2 *= w3;
  /* #75: @3 = sin(@4) */
  w3 = sin( w4 );
  /* #76: @2 = (@2*@3) */
  w2 *= w3;
  /* #77: @1 = (@1-@2) */
  w1 -= w2;
  /* #78: (@16[29] = @1) */
  for (rr=w16+29, ss=(&w1); rr!=w16+30; rr+=1) *rr = *ss++;
  /* #79: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #80: @2 = 1.71991e-08 */
  w2 = 1.7199142052564800e-08;
  /* #81: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #82: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #83: @2 = (@2*@3) */
  w2 *= w3;
  /* #84: @1 = (@1-@2) */
  w1 -= w2;
  /* #85: @2 = 1.18747e-08 */
  w2 = 1.1874674422694799e-08;
  /* #86: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #87: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #88: @2 = (@2*@3) */
  w2 *= w3;
  /* #89: @1 = (@1+@2) */
  w1 += w2;
  /* #90: @2 = 1.18747e-08 */
  w2 = 1.1874674422694799e-08;
  /* #91: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #92: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #93: @2 = (@2*@3) */
  w2 *= w3;
  /* #94: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #95: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #96: @2 = (@2*@3) */
  w2 *= w3;
  /* #97: @1 = (@1-@2) */
  w1 -= w2;
  /* #98: @2 = 5.75996e-08 */
  w2 = 5.7599641136459801e-08;
  /* #99: @3 = cos(@4) */
  w3 = cos( w4 );
  /* #100: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #101: @2 = (@2*@3) */
  w2 *= w3;
  /* #102: @3 = cos(@5) */
  w3 = cos( w5 );
  /* #103: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #104: @2 = (@2*@3) */
  w2 *= w3;
  /* #105: @1 = (@1+@2) */
  w1 += w2;
  /* #106: (@16[35] = @1) */
  for (rr=w16+35, ss=(&w1); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #107: @17 = zeros(6x6) */
  casadi_clear(w17, 36);
  /* #108: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #109: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #110: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #111: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #112: @1 = cos(@6) */
  w1 = cos( w6 );
  /* #113: (@21[0] = @1) */
  for (rr=w21+0, ss=(&w1); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #114: @1 = sin(@6) */
  w1 = sin( w6 );
  /* #115: @1 = (-@1) */
  w1 = (- w1 );
  /* #116: (@21[3] = @1) */
  for (rr=w21+3, ss=(&w1); rr!=w21+4; rr+=1) *rr = *ss++;
  /* #117: @1 = sin(@6) */
  w1 = sin( w6 );
  /* #118: (@21[1] = @1) */
  for (rr=w21+1, ss=(&w1); rr!=w21+2; rr+=1) *rr = *ss++;
  /* #119: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #120: (@21[4] = @6) */
  for (rr=w21+4, ss=(&w6); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #121: @6 = 1 */
  w6 = 1.;
  /* #122: (@21[8] = @6) */
  for (rr=w21+8, ss=(&w6); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #123: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #124: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #125: (@22[0] = @6) */
  for (rr=w22+0, ss=(&w6); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #126: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #127: (@22[6] = @6) */
  for (rr=w22+6, ss=(&w6); rr!=w22+7; rr+=1) *rr = *ss++;
  /* #128: @6 = 1 */
  w6 = 1.;
  /* #129: (@22[4] = @6) */
  for (rr=w22+4, ss=(&w6); rr!=w22+5; rr+=1) *rr = *ss++;
  /* #130: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #131: @6 = (-@6) */
  w6 = (- w6 );
  /* #132: (@22[2] = @6) */
  for (rr=w22+2, ss=(&w6); rr!=w22+3; rr+=1) *rr = *ss++;
  /* #133: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #134: (@22[8] = @6) */
  for (rr=w22+8, ss=(&w6); rr!=w22+9; rr+=1) *rr = *ss++;
  /* #135: @20 = mac(@21,@22,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #136: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #137: @6 = 1 */
  w6 = 1.;
  /* #138: (@21[0] = @6) */
  for (rr=w21+0, ss=(&w6); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #139: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #140: (@21[4] = @6) */
  for (rr=w21+4, ss=(&w6); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #141: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #142: @6 = (-@6) */
  w6 = (- w6 );
  /* #143: (@21[7] = @6) */
  for (rr=w21+7, ss=(&w6); rr!=w21+8; rr+=1) *rr = *ss++;
  /* #144: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #145: (@21[5] = @6) */
  for (rr=w21+5, ss=(&w6); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #146: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #147: (@21[8] = @6) */
  for (rr=w21+8, ss=(&w6); rr!=w21+9; rr+=1) *rr = *ss++;
  /* #148: @19 = mac(@20,@21,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #149: @23 = zeros(6x6) */
  casadi_clear(w23, 36);
  /* #150: @6 = 6.08415e-08 */
  w6 = 6.0841483860806802e-08;
  /* #151: (@23[14] = @6) */
  for (rr=w23+14, ss=(&w6); rr!=w23+15; rr+=1) *rr = *ss++;
  /* #152: @20 = @23[:18:6;:3] */
  for (rr=w20, ss=w23+0; ss!=w23+18; ss+=6) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #153: @18 = mac(@19,@20,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #154: (@17[:18:6;:3] = @18) */
  for (rr=w17+0, ss=w18; rr!=w17+18; rr+=6) for (tt=rr+0; tt!=rr+3; tt+=1) *tt = *ss++;
  /* #155: @18 = @23[18, 19, 20, 24, 25, 26, 30, 31, 32] */
  for (cii=casadi_s0, rr=w18, ss=w23; cii!=casadi_s0+9; ++cii) *rr++ = ss[*cii];
  /* #156: (@17[18, 19, 20, 24, 25, 26, 30, 31, 32] = @18) */
  for (cii=casadi_s0, rr=w17, ss=w18; cii!=casadi_s0+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #157: @18 = @23[:18:6;3:6] */
  for (rr=w18, ss=w23+0; ss!=w23+18; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #158: (@17[:18:6;3:6] = @18) */
  for (rr=w17+0, ss=w18; rr!=w17+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #159: @18 = @23[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s1, rr=w18, ss=w23; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #160: (@17[21, 22, 23, 27, 28, 29, 33, 34, 35] = @18) */
  for (cii=casadi_s1, rr=w17, ss=w18; cii!=casadi_s1+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #161: @16 = (@16+@17) */
  for (i=0, rr=w16, cs=w17; i<36; ++i) (*rr++) += (*cs++);
  /* #162: @15 = (@16\@15) */
  rr = w15;
  ss = w16;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[21], r[21], beta[6], w[12];
    casadi_qr(casadi_s3, ss, w, casadi_s4, v, casadi_s5, r, beta, casadi_s2, casadi_s2);
    casadi_qr_solve(rr, 6, 0, casadi_s4, v, casadi_s5, r, beta, casadi_s2, casadi_s2, w);
  }
  /* #163: @24 = zeros(6x1) */
  casadi_clear(w24, 6);
  /* #164: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #165: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #166: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #167: @6 = 6.16081e-08 */
  w6 = 6.1608076108510296e-08;
  /* #168: (@16[14] = @6) */
  for (rr=w16+14, ss=(&w6); rr!=w16+15; rr+=1) *rr = *ss++;
  /* #169: @6 = 1.49712e-06 */
  w6 = 1.4971213772915599e-06;
  /* #170: (@16[21] = @6) */
  for (rr=w16+21, ss=(&w6); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #171: @6 = 8.42431e-07 */
  w6 = 8.4243075663276500e-07;
  /* #172: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #173: @6 = 1.34018e-06 */
  w6 = 1.3401815483117601e-06;
  /* #174: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #175: @6 = 0 */
  w6 = 0.;
  /* #176: @1 = 0 */
  w1 = 0.;
  /* #177: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #178: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #179: @7 = input[1][2] */
  w7 = arg[1] ? arg[1][2] : 0;
  /* #180: @8 = input[1][3] */
  w8 = arg[1] ? arg[1][3] : 0;
  /* #181: @27 = vertcat(@6, @1, @2, @3, @7, @8) */
  rr=w27;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w8;
  /* #182: @26 = mac(@16,@27,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w27+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #183: @27 = zeros(6x1) */
  casadi_clear(w27, 6);
  /* #184: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #185: @6 = 1.33788e-06 */
  w6 = 1.3378842350641700e-06;
  /* #186: (@16[21] = @6) */
  for (rr=w16+21, ss=(&w6); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #187: @6 = 7.32462e-07 */
  w6 = 7.3246155912412005e-07;
  /* #188: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #189: @6 = 1.30715e-06 */
  w6 = 1.3071487746043900e-06;
  /* #190: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #191: @28 = @13[:6] */
  for (rr=w28, ss=w13+0; ss!=w13+6; ss+=1) *rr++ = *ss;
  /* #192: @27 = mac(@16,@28,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w28+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #193: @26 = (@26-@27) */
  for (i=0, rr=w26, cs=w27; i<6; ++i) (*rr++) -= (*cs++);
  /* #194: @27 = zeros(6x1) */
  casadi_clear(w27, 6);
  /* #195: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #196: @6 = 6.07979e-08 */
  w6 = 6.0797875597417800e-08;
  /* #197: (@16[14] = @6) */
  for (rr=w16+14, ss=(&w6); rr!=w16+15; rr+=1) *rr = *ss++;
  /* #198: @6 = 3.08457e-07 */
  w6 = 3.0845688169258201e-07;
  /* #199: (@16[21] = @6) */
  for (rr=w16+21, ss=(&w6); rr!=w16+22; rr+=1) *rr = *ss++;
  /* #200: @6 = 1.79781e-07 */
  w6 = 1.7978092198386399e-07;
  /* #201: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #202: @6 = 4.25094e-07 */
  w6 = 4.2509429652011002e-07;
  /* #203: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #204: @28 = @13[6:12] */
  for (rr=w28, ss=w13+6; ss!=w13+12; ss+=1) *rr++ = *ss;
  /* #205: @27 = mac(@16,@28,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w28+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #206: @26 = (@26-@27) */
  for (i=0, rr=w26, cs=w27; i<6; ++i) (*rr++) -= (*cs++);
  /* #207: @27 = zeros(6x1) */
  casadi_clear(w27, 6);
  /* #208: @6 = 1.03823e-07 */
  w6 = 1.0382277547832866e-07;
  /* #209: (@27[2] = @6) */
  for (rr=w27+2, ss=(&w6); rr!=w27+3; rr+=1) *rr = *ss++;
  /* #210: @26 = (@26+@27) */
  for (i=0, rr=w26, cs=w27; i<6; ++i) (*rr++) += (*cs++);
  /* #211: @29 = @26[:3] */
  for (rr=w29, ss=w26+0; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #212: @25 = mac(@19,@29,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #213: (@24[:3] = @25) */
  for (rr=w24+0, ss=w25; rr!=w24+3; rr+=1) *rr = *ss++;
  /* #214: @25 = @26[3:6] */
  for (rr=w25, ss=w26+3; ss!=w26+6; ss+=1) *rr++ = *ss;
  /* #215: (@24[3:6] = @25) */
  for (rr=w24+3, ss=w25; rr!=w24+6; rr+=1) *rr = *ss++;
  /* #216: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #217: @16 = zeros(6x6) */
  casadi_clear(w16, 36);
  /* #218: @6 = 1.18747e-08 */
  w6 = 1.1874674422694799e-08;
  /* #219: @6 = (@6*@12) */
  w6 *= w12;
  /* #220: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #221: @6 = (@6*@1) */
  w6 *= w1;
  /* #222: @1 = 2 */
  w1 = 2.;
  /* #223: @6 = (@6/@1) */
  w6 /= w1;
  /* #224: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #225: @1 = (@1*@12) */
  w1 *= w12;
  /* #226: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #227: @1 = (@1*@2) */
  w1 *= w2;
  /* #228: @2 = 2 */
  w2 = 2.;
  /* #229: @1 = (@1/@2) */
  w1 /= w2;
  /* #230: @6 = (@6-@1) */
  w6 -= w1;
  /* #231: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #232: @1 = (@1*@12) */
  w1 *= w12;
  /* #233: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #234: @1 = (@1*@2) */
  w1 *= w2;
  /* #235: @2 = 2 */
  w2 = 2.;
  /* #236: @1 = (@1/@2) */
  w1 /= w2;
  /* #237: @6 = (@6-@1) */
  w6 -= w1;
  /* #238: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #239: @1 = (@1*@12) */
  w1 *= w12;
  /* #240: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #241: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #242: @1 = (@1*@2) */
  w1 *= w2;
  /* #243: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #244: @1 = (@1*@2) */
  w1 *= w2;
  /* #245: @6 = (@6-@1) */
  w6 -= w1;
  /* #246: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #247: @1 = (@1*@12) */
  w1 *= w12;
  /* #248: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #249: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #250: @1 = (@1*@2) */
  w1 *= w2;
  /* #251: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #252: @1 = (@1*@2) */
  w1 *= w2;
  /* #253: @6 = (@6+@1) */
  w6 += w1;
  /* #254: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #255: @1 = (@1*@11) */
  w1 *= w11;
  /* #256: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #257: @1 = (@1*@2) */
  w1 *= w2;
  /* #258: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #259: @1 = (@1*@2) */
  w1 *= w2;
  /* #260: @6 = (@6+@1) */
  w6 += w1;
  /* #261: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #262: @1 = (@1*@11) */
  w1 *= w11;
  /* #263: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #264: @1 = (@1*@2) */
  w1 *= w2;
  /* #265: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #266: @1 = (@1*@2) */
  w1 *= w2;
  /* #267: @6 = (@6-@1) */
  w6 -= w1;
  /* #268: (@16[27] = @6) */
  for (rr=w16+27, ss=(&w6); rr!=w16+28; rr+=1) *rr = *ss++;
  /* #269: @6 = 1.18747e-08 */
  w6 = 1.1874674422694799e-08;
  /* #270: @6 = (@6*@11) */
  w6 *= w11;
  /* #271: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #272: @6 = (@6*@1) */
  w6 *= w1;
  /* #273: @1 = 2 */
  w1 = 2.;
  /* #274: @6 = (@6/@1) */
  w6 /= w1;
  /* #275: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #276: @1 = (@1*@11) */
  w1 *= w11;
  /* #277: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #278: @1 = (@1*@2) */
  w1 *= w2;
  /* #279: @2 = 2 */
  w2 = 2.;
  /* #280: @1 = (@1/@2) */
  w1 /= w2;
  /* #281: @6 = (@6-@1) */
  w6 -= w1;
  /* #282: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #283: @1 = (@1*@11) */
  w1 *= w11;
  /* #284: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #285: @1 = (@1*@2) */
  w1 *= w2;
  /* #286: @2 = 2 */
  w2 = 2.;
  /* #287: @1 = (@1/@2) */
  w1 /= w2;
  /* #288: @6 = (@6-@1) */
  w6 -= w1;
  /* #289: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #290: @1 = (@1*@11) */
  w1 *= w11;
  /* #291: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #292: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #293: @1 = (@1*@2) */
  w1 *= w2;
  /* #294: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #295: @1 = (@1*@2) */
  w1 *= w2;
  /* #296: @6 = (@6-@1) */
  w6 -= w1;
  /* #297: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #298: @1 = (@1*@11) */
  w1 *= w11;
  /* #299: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #300: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #301: @1 = (@1*@2) */
  w1 *= w2;
  /* #302: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #303: @1 = (@1*@2) */
  w1 *= w2;
  /* #304: @6 = (@6+@1) */
  w6 += w1;
  /* #305: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #306: @1 = (@1*@12) */
  w1 *= w12;
  /* #307: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #308: @1 = (@1*@2) */
  w1 *= w2;
  /* #309: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #310: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #311: @1 = (@1*@2) */
  w1 *= w2;
  /* #312: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #313: @1 = (@1*@2) */
  w1 *= w2;
  /* #314: @6 = (@6-@1) */
  w6 -= w1;
  /* #315: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #316: @1 = (@1*@12) */
  w1 *= w12;
  /* #317: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #318: @1 = (@1*@2) */
  w1 *= w2;
  /* #319: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #320: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #321: @1 = (@1*@2) */
  w1 *= w2;
  /* #322: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #323: @1 = (@1*@2) */
  w1 *= w2;
  /* #324: @6 = (@6+@1) */
  w6 += w1;
  /* #325: (@16[33] = @6) */
  for (rr=w16+33, ss=(&w6); rr!=w16+34; rr+=1) *rr = *ss++;
  /* #326: @6 = 1.71991e-08 */
  w6 = 1.7199142052564800e-08;
  /* #327: @6 = (@6*@12) */
  w6 *= w12;
  /* #328: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #329: @6 = (@6*@1) */
  w6 *= w1;
  /* #330: @1 = 2 */
  w1 = 2.;
  /* #331: @6 = (@6/@1) */
  w6 /= w1;
  /* #332: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #333: @1 = (@1*@12) */
  w1 *= w12;
  /* #334: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #335: @1 = (@1*@2) */
  w1 *= w2;
  /* #336: @2 = 2 */
  w2 = 2.;
  /* #337: @1 = (@1/@2) */
  w1 /= w2;
  /* #338: @6 = (@6-@1) */
  w6 -= w1;
  /* #339: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #340: @1 = (@1*@12) */
  w1 *= w12;
  /* #341: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #342: @1 = (@1*@2) */
  w1 *= w2;
  /* #343: @2 = 2 */
  w2 = 2.;
  /* #344: @1 = (@1/@2) */
  w1 /= w2;
  /* #345: @6 = (@6+@1) */
  w6 += w1;
  /* #346: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #347: @1 = (@1*@12) */
  w1 *= w12;
  /* #348: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #349: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #350: @1 = (@1*@2) */
  w1 *= w2;
  /* #351: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #352: @1 = (@1*@2) */
  w1 *= w2;
  /* #353: @6 = (@6+@1) */
  w6 += w1;
  /* #354: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #355: @1 = (@1*@12) */
  w1 *= w12;
  /* #356: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #357: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #358: @1 = (@1*@2) */
  w1 *= w2;
  /* #359: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #360: @1 = (@1*@2) */
  w1 *= w2;
  /* #361: @6 = (@6-@1) */
  w6 -= w1;
  /* #362: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #363: @1 = (@1*@11) */
  w1 *= w11;
  /* #364: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #365: @1 = (@1*@2) */
  w1 *= w2;
  /* #366: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #367: @1 = (@1*@2) */
  w1 *= w2;
  /* #368: @6 = (@6-@1) */
  w6 -= w1;
  /* #369: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #370: @1 = (@1*@11) */
  w1 *= w11;
  /* #371: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #372: @1 = (@1*@2) */
  w1 *= w2;
  /* #373: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #374: @1 = (@1*@2) */
  w1 *= w2;
  /* #375: @6 = (@6+@1) */
  w6 += w1;
  /* #376: (@16[22] = @6) */
  for (rr=w16+22, ss=(&w6); rr!=w16+23; rr+=1) *rr = *ss++;
  /* #377: @6 = 5.75996e-08 */
  w6 = 5.7599641136459801e-08;
  /* #378: @6 = (@6*@10) */
  w6 *= w10;
  /* #379: @1 = cos(@4) */
  w1 = cos( w4 );
  /* #380: @6 = (@6*@1) */
  w6 *= w1;
  /* #381: @1 = sin(@4) */
  w1 = sin( w4 );
  /* #382: @6 = (@6*@1) */
  w6 *= w1;
  /* #383: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #384: @1 = (@1*@10) */
  w1 *= w10;
  /* #385: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #386: @1 = (@1*@2) */
  w1 *= w2;
  /* #387: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #388: @1 = (@1*@2) */
  w1 *= w2;
  /* #389: @6 = (@6-@1) */
  w6 -= w1;
  /* #390: (@16[28] = @6) */
  for (rr=w16+28, ss=(&w6); rr!=w16+29; rr+=1) *rr = *ss++;
  /* #391: @6 = 1.71991e-08 */
  w6 = 1.7199142052564800e-08;
  /* #392: @6 = (@6*@10) */
  w6 *= w10;
  /* #393: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #394: @6 = (@6*@1) */
  w6 *= w1;
  /* #395: @1 = 2 */
  w1 = 2.;
  /* #396: @6 = (@6/@1) */
  w6 /= w1;
  /* #397: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #398: @1 = (@1*@10) */
  w1 *= w10;
  /* #399: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #400: @1 = (@1*@2) */
  w1 *= w2;
  /* #401: @2 = 2 */
  w2 = 2.;
  /* #402: @1 = (@1/@2) */
  w1 /= w2;
  /* #403: @6 = (@6-@1) */
  w6 -= w1;
  /* #404: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #405: @1 = (@1*@10) */
  w1 *= w10;
  /* #406: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #407: @1 = (@1*@2) */
  w1 *= w2;
  /* #408: @2 = 2 */
  w2 = 2.;
  /* #409: @1 = (@1/@2) */
  w1 /= w2;
  /* #410: @6 = (@6+@1) */
  w6 += w1;
  /* #411: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #412: @1 = (@1*@10) */
  w1 *= w10;
  /* #413: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #414: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #415: @1 = (@1*@2) */
  w1 *= w2;
  /* #416: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #417: @1 = (@1*@2) */
  w1 *= w2;
  /* #418: @6 = (@6+@1) */
  w6 += w1;
  /* #419: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #420: @1 = (@1*@10) */
  w1 *= w10;
  /* #421: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #422: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #423: @1 = (@1*@2) */
  w1 *= w2;
  /* #424: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #425: @1 = (@1*@2) */
  w1 *= w2;
  /* #426: @6 = (@6-@1) */
  w6 -= w1;
  /* #427: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #428: @1 = (@1*@12) */
  w1 *= w12;
  /* #429: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #430: @1 = (@1*@2) */
  w1 *= w2;
  /* #431: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #432: @1 = (@1*@2) */
  w1 *= w2;
  /* #433: @6 = (@6-@1) */
  w6 -= w1;
  /* #434: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #435: @1 = (@1*@12) */
  w1 *= w12;
  /* #436: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #437: @1 = (@1*@2) */
  w1 *= w2;
  /* #438: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #439: @1 = (@1*@2) */
  w1 *= w2;
  /* #440: @6 = (@6+@1) */
  w6 += w1;
  /* #441: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #442: @1 = (@1*@12) */
  w1 *= w12;
  /* #443: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #444: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #445: @1 = (@1*@2) */
  w1 *= w2;
  /* #446: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #447: @1 = (@1*@2) */
  w1 *= w2;
  /* #448: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #449: @1 = (@1*@2) */
  w1 *= w2;
  /* #450: @6 = (@6-@1) */
  w6 -= w1;
  /* #451: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #452: @1 = (@1*@12) */
  w1 *= w12;
  /* #453: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #454: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #455: @1 = (@1*@2) */
  w1 *= w2;
  /* #456: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #457: @1 = (@1*@2) */
  w1 *= w2;
  /* #458: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #459: @1 = (@1*@2) */
  w1 *= w2;
  /* #460: @6 = (@6+@1) */
  w6 += w1;
  /* #461: (@16[34] = @6) */
  for (rr=w16+34, ss=(&w6); rr!=w16+35; rr+=1) *rr = *ss++;
  /* #462: @6 = 5.75996e-08 */
  w6 = 5.7599641136459801e-08;
  /* #463: @6 = (@6*@11) */
  w6 *= w11;
  /* #464: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #465: @6 = (@6*@1) */
  w6 *= w1;
  /* #466: @1 = 2 */
  w1 = 2.;
  /* #467: @6 = (@6/@1) */
  w6 /= w1;
  /* #468: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #469: @1 = (@1*@11) */
  w1 *= w11;
  /* #470: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #471: @1 = (@1*@2) */
  w1 *= w2;
  /* #472: @2 = 2 */
  w2 = 2.;
  /* #473: @1 = (@1/@2) */
  w1 /= w2;
  /* #474: @6 = (@6-@1) */
  w6 -= w1;
  /* #475: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #476: @1 = (@1*@11) */
  w1 *= w11;
  /* #477: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #478: @1 = (@1*@2) */
  w1 *= w2;
  /* #479: @2 = 2 */
  w2 = 2.;
  /* #480: @1 = (@1/@2) */
  w1 /= w2;
  /* #481: @6 = (@6-@1) */
  w6 -= w1;
  /* #482: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #483: @1 = (@1*@11) */
  w1 *= w11;
  /* #484: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #485: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #486: @1 = (@1*@2) */
  w1 *= w2;
  /* #487: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #488: @1 = (@1*@2) */
  w1 *= w2;
  /* #489: @6 = (@6+@1) */
  w6 += w1;
  /* #490: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #491: @1 = (@1*@11) */
  w1 *= w11;
  /* #492: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #493: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #494: @1 = (@1*@2) */
  w1 *= w2;
  /* #495: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #496: @1 = (@1*@2) */
  w1 *= w2;
  /* #497: @6 = (@6-@1) */
  w6 -= w1;
  /* #498: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #499: @1 = (@1*@12) */
  w1 *= w12;
  /* #500: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #501: @1 = (@1*@2) */
  w1 *= w2;
  /* #502: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #503: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #504: @1 = (@1*@2) */
  w1 *= w2;
  /* #505: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #506: @1 = (@1*@2) */
  w1 *= w2;
  /* #507: @6 = (@6+@1) */
  w6 += w1;
  /* #508: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #509: @1 = (@1*@12) */
  w1 *= w12;
  /* #510: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #511: @1 = (@1*@2) */
  w1 *= w2;
  /* #512: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #513: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #514: @1 = (@1*@2) */
  w1 *= w2;
  /* #515: @2 = sin(@4) */
  w2 = sin( w4 );
  /* #516: @1 = (@1*@2) */
  w1 *= w2;
  /* #517: @6 = (@6-@1) */
  w6 -= w1;
  /* #518: (@16[23] = @6) */
  for (rr=w16+23, ss=(&w6); rr!=w16+24; rr+=1) *rr = *ss++;
  /* #519: @6 = 5.75996e-08 */
  w6 = 5.7599641136459801e-08;
  /* #520: @6 = (@6*@10) */
  w6 *= w10;
  /* #521: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #522: @6 = (@6*@1) */
  w6 *= w1;
  /* #523: @1 = 2 */
  w1 = 2.;
  /* #524: @6 = (@6/@1) */
  w6 /= w1;
  /* #525: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #526: @1 = (@1*@10) */
  w1 *= w10;
  /* #527: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #528: @1 = (@1*@2) */
  w1 *= w2;
  /* #529: @2 = 2 */
  w2 = 2.;
  /* #530: @1 = (@1/@2) */
  w1 /= w2;
  /* #531: @6 = (@6-@1) */
  w6 -= w1;
  /* #532: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #533: @1 = (@1*@10) */
  w1 *= w10;
  /* #534: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #535: @1 = (@1*@2) */
  w1 *= w2;
  /* #536: @2 = 2 */
  w2 = 2.;
  /* #537: @1 = (@1/@2) */
  w1 /= w2;
  /* #538: @6 = (@6-@1) */
  w6 -= w1;
  /* #539: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #540: @1 = (@1*@10) */
  w1 *= w10;
  /* #541: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #542: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #543: @1 = (@1*@2) */
  w1 *= w2;
  /* #544: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #545: @1 = (@1*@2) */
  w1 *= w2;
  /* #546: @6 = (@6+@1) */
  w6 += w1;
  /* #547: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #548: @1 = (@1*@10) */
  w1 *= w10;
  /* #549: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #550: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #551: @1 = (@1*@2) */
  w1 *= w2;
  /* #552: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #553: @1 = (@1*@2) */
  w1 *= w2;
  /* #554: @6 = (@6-@1) */
  w6 -= w1;
  /* #555: @1 = 1.71991e-08 */
  w1 = 1.7199142052564800e-08;
  /* #556: @1 = (@1*@12) */
  w1 *= w12;
  /* #557: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #558: @1 = (@1*@2) */
  w1 *= w2;
  /* #559: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #560: @1 = (@1*@2) */
  w1 *= w2;
  /* #561: @6 = (@6+@1) */
  w6 += w1;
  /* #562: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #563: @1 = (@1*@12) */
  w1 *= w12;
  /* #564: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #565: @1 = (@1*@2) */
  w1 *= w2;
  /* #566: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #567: @1 = (@1*@2) */
  w1 *= w2;
  /* #568: @6 = (@6-@1) */
  w6 -= w1;
  /* #569: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #570: @1 = (@1*@12) */
  w1 *= w12;
  /* #571: @2 = cos(@4) */
  w2 = cos( w4 );
  /* #572: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #573: @1 = (@1*@2) */
  w1 *= w2;
  /* #574: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #575: @1 = (@1*@2) */
  w1 *= w2;
  /* #576: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #577: @1 = (@1*@2) */
  w1 *= w2;
  /* #578: @6 = (@6+@1) */
  w6 += w1;
  /* #579: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #580: @1 = (@1*@12) */
  w1 *= w12;
  /* #581: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #582: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #583: @1 = (@1*@12) */
  w1 *= w12;
  /* #584: @12 = cos(@5) */
  w12 = cos( w5 );
  /* #585: @1 = (@1*@12) */
  w1 *= w12;
  /* #586: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #587: @1 = (@1*@12) */
  w1 *= w12;
  /* #588: @6 = (@6-@1) */
  w6 -= w1;
  /* #589: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #590: @1 = (@1*@11) */
  w1 *= w11;
  /* #591: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #592: @1 = (@1*@12) */
  w1 *= w12;
  /* #593: @12 = sin(@4) */
  w12 = sin( w4 );
  /* #594: @1 = (@1*@12) */
  w1 *= w12;
  /* #595: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #596: @1 = (@1*@12) */
  w1 *= w12;
  /* #597: @6 = (@6-@1) */
  w6 -= w1;
  /* #598: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #599: @1 = (@1*@11) */
  w1 *= w11;
  /* #600: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #601: @1 = (@1*@12) */
  w1 *= w12;
  /* #602: @12 = sin(@4) */
  w12 = sin( w4 );
  /* #603: @1 = (@1*@12) */
  w1 *= w12;
  /* #604: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #605: @1 = (@1*@12) */
  w1 *= w12;
  /* #606: @6 = (@6+@1) */
  w6 += w1;
  /* #607: (@16[29] = @6) */
  for (rr=w16+29, ss=(&w6); rr!=w16+30; rr+=1) *rr = *ss++;
  /* #608: @6 = 1.71991e-08 */
  w6 = 1.7199142052564800e-08;
  /* #609: @6 = (@6*@11) */
  w6 *= w11;
  /* #610: @1 = cos(@5) */
  w1 = cos( w5 );
  /* #611: @6 = (@6*@1) */
  w6 *= w1;
  /* #612: @1 = sin(@5) */
  w1 = sin( w5 );
  /* #613: @6 = (@6*@1) */
  w6 *= w1;
  /* #614: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #615: @1 = (@1*@11) */
  w1 *= w11;
  /* #616: @12 = cos(@5) */
  w12 = cos( w5 );
  /* #617: @1 = (@1*@12) */
  w1 *= w12;
  /* #618: @12 = sin(@5) */
  w12 = sin( w5 );
  /* #619: @1 = (@1*@12) */
  w1 *= w12;
  /* #620: @6 = (@6-@1) */
  w6 -= w1;
  /* #621: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #622: @1 = (@1*@10) */
  w1 *= w10;
  /* #623: @12 = cos(@4) */
  w12 = cos( w4 );
  /* #624: @1 = (@1*@12) */
  w1 *= w12;
  /* #625: @12 = cos(@5) */
  w12 = cos( w5 );
  /* #626: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #627: @1 = (@1*@12) */
  w1 *= w12;
  /* #628: @12 = sin(@4) */
  w12 = sin( w4 );
  /* #629: @1 = (@1*@12) */
  w1 *= w12;
  /* #630: @6 = (@6+@1) */
  w6 += w1;
  /* #631: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #632: @1 = (@1*@10) */
  w1 *= w10;
  /* #633: @10 = cos(@4) */
  w10 = cos( w4 );
  /* #634: @1 = (@1*@10) */
  w1 *= w10;
  /* #635: @10 = cos(@5) */
  w10 = cos( w5 );
  /* #636: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #637: @1 = (@1*@10) */
  w1 *= w10;
  /* #638: @10 = sin(@4) */
  w10 = sin( w4 );
  /* #639: @1 = (@1*@10) */
  w1 *= w10;
  /* #640: @6 = (@6-@1) */
  w6 -= w1;
  /* #641: @1 = 1.18747e-08 */
  w1 = 1.1874674422694799e-08;
  /* #642: @1 = (@1*@11) */
  w1 *= w11;
  /* #643: @10 = cos(@4) */
  w10 = cos( w4 );
  /* #644: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #645: @1 = (@1*@10) */
  w1 *= w10;
  /* #646: @10 = cos(@5) */
  w10 = cos( w5 );
  /* #647: @1 = (@1*@10) */
  w1 *= w10;
  /* #648: @10 = sin(@5) */
  w10 = sin( w5 );
  /* #649: @1 = (@1*@10) */
  w1 *= w10;
  /* #650: @6 = (@6+@1) */
  w6 += w1;
  /* #651: @1 = 5.75996e-08 */
  w1 = 5.7599641136459801e-08;
  /* #652: @1 = (@1*@11) */
  w1 *= w11;
  /* #653: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #654: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #655: @1 = (@1*@4) */
  w1 *= w4;
  /* #656: @4 = cos(@5) */
  w4 = cos( w5 );
  /* #657: @1 = (@1*@4) */
  w1 *= w4;
  /* #658: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #659: @1 = (@1*@5) */
  w1 *= w5;
  /* #660: @6 = (@6-@1) */
  w6 -= w1;
  /* #661: (@16[35] = @6) */
  for (rr=w16+35, ss=(&w6); rr!=w16+36; rr+=1) *rr = *ss++;
  /* #662: @27 = @13[6:12] */
  for (rr=w27, ss=w13+6; ss!=w13+12; ss+=1) *rr++ = *ss;
  /* #663: @26 = mac(@16,@27,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w27+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #664: @24 = (@24-@26) */
  for (i=0, rr=w24, cs=w26; i<6; ++i) (*rr++) -= (*cs++);
  /* #665: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #666: @6 = 1.03823e-07 */
  w6 = 1.0382277547832866e-07;
  /* #667: (@26[2] = @6) */
  for (rr=w26+2, ss=(&w6); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #668: @24 = (@24-@26) */
  for (i=0, rr=w24, cs=w26; i<6; ++i) (*rr++) -= (*cs++);
  /* #669: @14 = mac(@15,@24,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w15+j, tt=w24+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #670: (@0[6:12] = @14) */
  for (rr=w0+6, ss=w14; rr!=w0+12; rr+=1) *rr = *ss++;
  /* #671: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 267;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
